function [samples tags unique_tags] = tagUNComplexActionsDataset(samples)

orig_class_names = {'Saludar', ...
    'agacharse', ...
    'alzar mancuernas', ...
    'aplaudir', ...
    'beber', ...
    'borrar tablero', ...
    'caminar', ...
    'caminar_aplaudir', ...
    'caminar_saludar', ...
    'comer snack', ...
    'dar vueltas', ...
    'estar de pie', ...
    'hablar por telefono', ...
    'lanzar', ...
    'leer revista', ...
    'patear', ...
    'peinarse', ...
    'puno de frente', ...
    'rascarse la cabeza', ...
    'recoger del suelo', ...
    'saltar', ...
    'saludo oriental', ...
    'telefono_rascarse cabeza', ...
    'telefono_recoger', ...
    'trotar'};

unique_tags = unique({'WaveHand', ...
    'Squat', ...
    'ArmCurl', ...
    'Clap', ...
    'Drink', ...
    'EraseWhiteboard', ...
    'Walk', 'Turn', ...
    'Walk' , 'Clap', ...
    'Walk', 'WaveHand', 'Turn', ...
    'EatSnack', ...
    'Turn', ...
    'Stand', ...
    'TalkPhone', ...
    'Throw', ...
    'Read', ...
    'Kick', ...
    'CombHair', ...
    'Jab', ...
    'ScratchHead', ...
    'PickUp', ...
    'Jump', ...
    'Bow', ...
    'TalkPhone', 'ScratchHead', ...
    'TalkPhone', 'PickUp', ...
    'Jog', 'Turn'});

tags = {'WaveHand', ...
    'Squat', ...
    'ArmCurl', ...
    'Clap', ...
    'Drink', ...
    'EraseWhiteboard', ...
    {'Walk', 'Turn'}, ...
    {'Walk' , 'Clap'}, ...
    {'Walk', 'WaveHand', 'Turn'}, ...
    'EatSnack', ...
    'Turn', ...
    'Stand', ...
    'TalkPhone', ...
    'Throw', ...
    'Read', ...
    'Kick', ...
    'CombHair', ...
    'Jab', ...
    'ScratchHead', ...
    'PickUp', ...
    'Jump', ...
    'Bow', ...
    {'TalkPhone', 'ScratchHead'}, ...
    {'TalkPhone', 'PickUp'}, ...
    {'Jog', 'Turn'}};

number_classes = numel(orig_class_names);
number_tags = numel(unique_tags);
active_tags = zeros(number_classes, number_tags);
for cidx = 1:number_classes
    for tidx = 1:number_tags
        tags_idx = find(strcmpi(tags{cidx}, unique_tags{tidx}),1);
        if ~isempty(tags_idx)
            active_tags(cidx, tidx) = 1;
        end
    end
end

for sidx = 1:numel(samples)
    class_name_idx = find(strcmp(orig_class_names,samples(sidx).class_name));
    current_tags = active_tags(class_name_idx,:);
    samples(sidx).active_tags = current_tags;
    samples(sidx).active_tags_names = tags{class_name_idx};
end
